---

#- name: install android-sdk-linux

- hosts: devservers 
  vars:
  - base_path: /u01/jenkins
  - api_ver: 25 
  - system-images: system-images;android-{{ api_ver }};google_apis;x86_64  

  gather_facts: False


  tasks:
    # - name: Install packages to install android sdk
    #   yum: name={{ item }} state=installed
    #   with_items:
    #     - glibc.i686
    #     - libstdc++-static
    #     - glibc-devel.i686
    #     - zlib.i686
    #     - zlib-devel.i686
    #     - ncurses-devel.i686
    #     - libX11-devel.i686
    #     - libXrender.i686
    #     - ld-linux.so.2
    #       sudo yum install mesa-libGL-devel
    #       sudo yum install libpulse.so.0


    #          sudo cp -a $ANDROID_HOME/emulator/lib64/qt/lib/. /usr/lib64/   !!!!!!!!!!!!!!


    # - name: Install Java
    #   yum: name={{ item }} state=installed
    #   with_items:
    #     - java-1.8.0-openjdk
    #     - java-1.8.0-openjdk-devel
  

    - name: Download sdk tools
      get_url: >
          url=https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
          dest={{ base_path }}/android-sdk.zip

    - name: Create Dir
      file:
        path: "{{ base_path }}/android-sdk/"
        state: directory

    - name: Unarchive sdk                                
      unarchive: 
        remote_src: yes
        src: "{{ base_path }}/android-sdk.zip"
        dest: "{{ base_path }}/android-sdk/"
        #creates: {{ base_path }}/android-sdk/

    - name: Mode File
      file:
        path: "{{ base_path }}/android-sdk/"
        # owner: akstas84
        # group: akstas84
        mode: 0755
        recurse: yes


    # - name: Set envs for android sdk
    #   copy: >
    #     src=envsdk.sh
    #     dest=/etc/profile.d/envsdk.sh  

###################################################
    - name: Accept Android SDK licenses 
      shell: yes | {{ base_path }}/android-sdk/tools/bin/sdkmanager --licenses

    - name: Install Android SDK Components
      shell: "{{ base_path }}/android-sdk/tools/bin/sdkmanager \"{{item}}\""
    #   #shell: (while sleep 3; do echo "y"; done) | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
      with_items:
        - tools
        - platform-tools
        - build-tools;27.0.3
        - platforms;android-{{ api_ver }}
        - "{{ system-images }}"

    - name: Create AVD
      shell: "{{ base_path }}/android-sdk/tools/bin/avdmanager create avd -n android-25 -k \"{{ system-images }}\" "
    #   #shell: (while sleep 3; do echo "y"; done) | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
      
    # - debug:
    #     var: shell_result.stdout_lines  
    #     #- android-23
    #     # - extra-bin/{{ base_path }}/android-sdk/bin/id-support
    #     # - extra-google-m2repository
    #     # - sys-img-x86_64-android-23
        
###################################################


    # - name: Install Android SDK Components 24
    #   #shell: echo y | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
    #   #shell: ( while [ 1 ]; do sleep 5; echo y; done ) | sudo /home/android-sdk-linux/tools/android update sdk --all --no-ui -t {{item}}
    #   shell: (while sleep 3; do echo "y"; done) | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
    #   with_items:
    #     - tools
    #     - platform-tool
    #     - build-tools

    # - name: Install Android SDK Components 25-27
    #   #shell: echo y | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
    #   #shell: ( while [ 1 ]; do sleep 5; echo y; done ) | sudo /home/android-sdk-linux/tools/android update sdk --all --no-ui -t {{item}}
    #   shell: (while sleep 3; do echo "y"; done) | /home/android-sdk-linux/tools/android update sdk -a --no-ui --filter {{item}}
    #   with_items:
    #     - tools
    #     - platform-tool
    #     - build-tools        


        # - extra-google-google_play_services
        # - extra-android-m2repository

# sudo ./android update sdk --all --no-ui -t 
# tools
# platform-tool
# build-tools-23.0.1
# android-23
# extra-android-support
# extra-android-m2repository
# sys-img-x86-android-23
# sys-img-x86_64-android-23



    # - name: Install Android SDKs
    #   shell: echo y | android update sdk -u -a -t "{{ item }}" 
    #   with_items:
# sudo ./android update sdk --all --no-ui -t 
         # - tools,
         # - platform-tool,
         # - build-tools-23.0.1,
         # - android-23,
         # - extra-android-support,
         # - extra-android-m2repository,
         # - sys-img-x86-android-23,
         # - sys-img-x86_64-android-23

        # - tools
        # - platform-tools
        # - build-tools--27.0.3
         # - android-23
         # - sys-img-x86_64-android-23
         # - sys-img-x86-android-24
         # - extra-google-m2repository
         # - extra-android-support
         # - extra-android-supportsys
         # - extra-android-m2repository


