---

- name: install android-sdk-linux

  hosts: devservers

  tasks:
    - name: Install packages to install android sdk
      yum: name={{ item }} state=installed
      with_items:
        - glibc.i686
        - libstdc++-static
        - glibc-devel.i686
        - zlib.i686
        - zlib-devel.i686
        - ncurses-devel.i686
        - libX11-devel.i686
        - libXrender.i686
        - ld-linux.so.2


    - name: Install Java
      yum: name={{ item }} state=installed
      with_items:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
  

    - name: Download sdk tools
      get_url: >
          url=http://dl.google.com/android/android-sdk_r24.2-linux.tgz
          dest=/home/android-sdk_r24.2-linux.tar.gz


    - name: Unarchive sdk                                
      unarchive: 
        remote_src: yes
        src: /home/android-sdk_r24.2-linux.tar.gz
        dest: /home


    - name: Set envs for android sdk
      copy: >
        src=envsdk.sh
        dest=/etc/profile.d/envsdk.sh  


    - name: Install Android SDKs
      shell: echo y | android update sdk -u -a -t "{{ item }}" 
      with_items:
        - tools
        - platform-tools
        - build-tools--24.0.1
        - android-24
        - sys-img-x86_64-android-24
          sys-img-x86-android-24
        - extra-google-m2repository
        - extra-android-support
        - extra-android-supportsys
        - extra-android-m2repository