---

- name: install Android SDK

  hosts: devservers

  tasks:
    - name: Download Android SDK
      action: get_url url=https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip dest=/tmp/android.tgz

      - name: Make opt dir for user
      action: file path=/opt/adt/ state=directory mode=0777

      - name: Unpack Android SDK
      action: unarchive copy=no src=/tmp/android.tgz dest=/opt/adt/ creates=/opt/adt//android-sdk-linux

      - name: Chown files
      action: file path=/opt/adt/android-sdk-linux recurse=yes state=directory

      - name: Install Android SDK
      action: shell creates=/opt/adt/android-sdk-linux/tools echo y | /opt/adt/android-sdk-linux/tools/android

      - name: Configure Android SDK paths
      action: lineinfile dest=/home/vagrant/.bashrc line="{{ item }}"
      with_items:
        - 'export ANDROID_HOME=/opt/adt/android-sdk-linux'
        - 'export ANDROID_TOOLS=$ANDROID_HOME/tools/'
        - 'export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools/'
        - 'export PATH=$PATH:$ANDROID_TOOLS:$ANDROID_PLATFORM_TOOLS'
