---

- name: install git

  hosts: devservers

  gather_facts: False

  vars:
    - packages: ["git"]

  tasks:
    - name: Installing {{ packages }} on {{ hostname }}
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"