---

- name: install git

  hosts: devservers

  gather_facts: False

  vars:
    - packages: ["git"]

  tasks:
    - name: Installing Git on host
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"