---

- name: install jenkins

  hosts: devservers

  tasks:
    - name: stop firewall
      service: name=firewalld state=stopped enabled=no
    
    - name: disbale on iptable on boot
      service: name=firewalld enabled=no

    - name: install wget
      yum: name=wget state=present

    - name: Install Java
      yum: name={{ item }} state=installed
      with_items:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel  

    - name: add repo
      get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

    - name: Add Jenkins repo GPG key
      rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org.key state=present

    - name: install jenkins
      yum: name=jenkins state=present

    - name: start jenkins service
      service: name=jenkins state=started enabled=yes



########################################################

      # Initial script off
        # /var/lib/jenkins/secrets/initialAdminPassword

      # Getting Started Auto Plugin Install 
        # Ant Plugin
        # Build Timeout
        # Email Extension Plugin
        # GitHub Branch Source Plugin
        # Gradle Plugin
        # LDAP Plugin
        # Matrix Authorization Strategy Plugin
        # OWASP Markup Formatter Plugin
        # PAM Authentication plugin
        # Pipeline
        # Pipeline GitHub Groovy Libraries
        # SSH Slaves plugin
        # Subversion Plug-in
        # Timestamper
        # Workspace Cleanup Plugin

