---

- name: "Disabled Selinux and Iptables"

  hosts: devservers

  tasks:

    - name:  "Disable SELinux"
      selinux:
        state: disabled

    - name: "Stop Firewall"
      service: name=firewalld state=stopped enabled=no
    
    - name: "Disbale on Firewall on boot"
      service: name=firewalld enabled=no

    - name: Restart server
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true  